pipeline {

    agent any
    
    stages {
        stage("Build Django App") {
            steps {
                sh 'sudo docker-compose -f DjangoAPI/docker-compose.yml up -d --build'
            }
        }
    }
}