pipeline {

    agent any
    
    stages {
        stage("Build Django App") {
            steps {
                sh 'sudo docker-compose up -f ./DjangoAPI/docker-compose.yml -d —build'
            }
        }
    }
}