# Generated by Django 4.1.2 on 2022-10-19 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='heartDiseasePrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_id', models.IntegerField()),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=15)),
                ('cp', models.CharField(choices=[('typical angina', 'typical angina'), ('asymptomatic', 'asymptomatic'), ('non-anginal', 'non-anginal'), ('atypical angina', 'atypical angina')], max_length=15)),
                ('trestbps', models.IntegerField()),
                ('chol', models.IntegerField()),
                ('fbs', models.CharField(choices=[('TRUE', 'TRUE'), ('FALSE', 'FALSE')], max_length=15)),
                ('restecg', models.CharField(choices=[('lv hypertrophy', 'lv hypertrophy'), ('normal', 'normal'), ('st-t abnormality', 'st-t abnormality')], max_length=30)),
                ('thalch', models.IntegerField()),
                ('exang', models.CharField(choices=[('TRUE', 'TRUE'), ('FALSE', 'FALSE')], max_length=15)),
                ('oldpeak', models.DecimalField(decimal_places=5, max_digits=5)),
                ('slope', models.CharField(choices=[('downsloping', 'downsloping'), ('flat', 'flat'), ('upsloping', 'upsloping')], max_length=15)),
                ('ca', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3')], max_length=15)),
                ('thal', models.CharField(choices=[('fixed defect', 'fixed defect'), ('normal', 'normal'), ('reversable defect', 'reversable defect')], max_length=30)),
            ],
        ),
    ]
