# Generated by Django 4.1.2 on 2022-10-20 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heartdiseaseprediction',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='heartdiseaseprediction',
            name='chol',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='heartdiseaseprediction',
            name='form_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='heartdiseaseprediction',
            name='oldpeak',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='heartdiseaseprediction',
            name='thalch',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='heartdiseaseprediction',
            name='trestbps',
            field=models.IntegerField(default=0),
        ),
    ]
