# Generated by Django 4.1.2 on 2022-10-26 08:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyAPI', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='heartdiseaseprediction',
            name='patient',
        ),
        migrations.AddField(
            model_name='heartdiseaseprediction',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
