# Generated by Django 4.1.2 on 2022-10-23 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyAPI', '0002_alter_heartdiseaseprediction_age_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='heartdiseaseprediction',
            old_name='gender',
            new_name='sex',
        ),
    ]
