# Generated by Django 4.1.2 on 2022-10-27 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyAPI', '0009_remove_admin_phone_number_remove_doctor_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heartdiseaseprediction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='%d/%m/%Y %H:%M:%S'),
        ),
    ]
