# Generated by Django 4.1.2 on 2022-10-27 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyAPI', '0010_alter_heartdiseaseprediction_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heartdiseaseprediction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='%d/%m/%Y %H:%M'),
        ),
    ]
